### ISSUE TITLE
localhost connection refused

### ISSUE THREAD

**Issue by natxopedreira** [patrickjquinn/P-Brain.ai-RasPi#1]
Hi, i just want to run this on OSX, and im getting this error.... maybe im doing something wrong?

P-Brain Says: You can also type your command into the terminal!
Hey Brain, What is the weather in Paris
{ Error: connect ECONNREFUSED 127.0.0.1:4567
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4567 }
(node:16074) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNREFUSED 127.0.0.1:4567

thanks

**Comment by patrickjquinn** [comment]
You need to start the server first: Go to https://github.com/patrickjquinn/P-Brain.ai and follow the instructions and then start this client :)

**Comment by natxopedreira** [comment]
Thanks!! sorry for the inconvenience.

**Comment by patrickjquinn** [comment]
No problem! Thats what i'm here for :)
