### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by natxopedreira** [patrickjquinn/P-Brain.ai-RasPi#4]
first thanks for your work, not only coding but also for your videos explaining how the system works, its super!

As my spoken english its not good i was not able to make the system respond to my voice so i want to change the language. Its possible to use in another language?

For example to tell me the current time, i changed the keywords to detect the phrase in spanish and in the response i changed the voice (im on OSX) to a spanish one. So in the console i typped the spanish sentence to get the time and the system responds the time in spanish.. cool

But i was not able to make the system recognize my sentences spoken, what im missing?

also dont know if this its the correct place to ask questions, if not please let me know. I have access to an aldebaran pepper robot and my goal its to use your system as background and use the robot as an interface to tell me the responses.

Thanks again, this its great and fun!!

**Comment by natxopedreira** [comment]
found it, need to do a new hotword detection in snowboy using spanish and the word.

**Comment by patrickjquinn** [comment]
Sorry for the delayed response!  If you have any further questions on getting snowboy working with Spanish let me know :)

I know you found it, but for people wishing to do so in future; the language is changed by setting `lang=en-us` to `lang=es-es` on line 84 (i.e the wit.ai api call) of `client.js`

**Comment by natxopedreira** [comment]
thanks! sadly the speech recognition in Spanish seems very poor

**Comment by patrickjquinn** [comment]
The speech recognition API in use is struggling at the moment, try back again during working hours to allow them time to fix it :)

**Comment by patrickjquinn** [comment]
Also try speaking slower (Spanish is spoken insanely quickly in comparison to English...so is French actually) so that the API can keep up :D

**Comment by natxopedreira** [comment]
Also tried the server only with the chrome client, the speech recognition works better but the response time its super slow right now. So i will do what you said and try on working hours, thanks again
