### ISSUE TITLE
Errors during auto install

### ISSUE THREAD

**Issue by hemalchevli** [patrickjquinn/P-Brain.ai-RasPi#5]
Hi,
I tried out the auto installer script on Pi running Jessie-lite. USB sound card was not connected during installation, I connected it and rebooted Pi, but getting error same as before connecting sound card. 
I've created a gist for the install log and also printed out the npm-debug.log 
Here is the log.
https://gist.github.com/hemalchevli/c4d06214a56208215c779e8640222a0c

Thank you
Cheers!

**Comment by patrickjquinn** [comment]
Hi there,

```
Cloing P-Brain.ai server...
Cloning into 'P-Brain.ai'...
remote: Counting objects: 740, done.
remote: Compressing objects: 100% (36/36), done.
error: RPC failed; result=56, HTTP code = 200| 13.00 KiB/s
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
cp: cannot stat ‘./P-Brain.ai/*’: No such file or directory
```

This shows there was a network error whilst pulling one of the repositories and thats why it failed :( The script runs fine on my device (Just tested) so could you delete the project and try running again, this time maybe with `sudo` before it?

**Comment by hemalchevli** [comment]
It worked.
Thanks
