### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:4567

### ISSUE THREAD

**Issue by GlennSchnieders** [patrickjquinn/P-Brain.ai-RasPi#6]
After I type a command i get following error `Error: connect ECONNREFUSED 127.0.0.1:4567`. I looked over in the client.js file, but I can't see where I can change that.

**Comment by patrickjquinn** [comment]
How are you started the clinet? On what machine etc? 

I suspect this is the fact that the P-Brain server isn't running
